### ISSUE TITLE
redis extension ignores igbinary when installed together (pre-built binary lacks support)

### ISSUE THREAD

**Issue by error1001es** [swoole/docker-swoole#64]
When installing redis and igbinary in the same command, the installer prefers a pre-built binary for redis. This pre-built binary is compiled without igbinary support.

Steps to Reproduce
Dockerfile:
```
FROM phpswoole/swoole:6.1.4-php8.4-alpine
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
RUN install-php-extensions igbinary redis
```
Undefined constant Redis::SERIALIZER_IGBINARY 

```
FROM php:8.4.12-alpine
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
RUN install-php-extensions igbinary redis
```
works good

**Comment by liulyn** [comment]
邮件已收到 谢谢！

**Comment by deminy** [comment]
Thanks for the report, and sorry for the slow follow-up. I looked into this properly — the behavior is real, but the cause isn't a pre-built binary.

## What actually happens

`install-php-extensions` compiles from source; `relay` is the only extension it ever fetches pre-built. What it *does* do is skip extensions PHP already has:

```
### WARNING Module already installed: redis ###
```

Our images ship phpredis pre-installed, so that warning (on stderr, exit code 0) is all you get: `igbinary` gets installed, redis is left exactly as it was, and `Redis::SERIALIZER_IGBINARY` stays undefined because it's gated at compile time behind `#ifdef HAVE_REDIS_IGBINARY`. On `php:8.4-alpine` there is no redis yet, so it gets built from source and igbinary is picked up automatically. That's the entire difference between your two Dockerfiles.

The decisive part of the workaround I posted earlier is the **uninstall** — removing redis is what forces it to be rebuilt. Installing `igbinary` alongside it isn't enough on its own, and the order inside the command makes no difference either (`install-php-extensions` already moves `igbinary` to the front of its own list). So this remains the way to do it today:

```Dockerfile
RUN set -ex && \
    rm -f "$(php-config --ini-dir)/docker-php-ext-redis.ini" && \
    pecl uninstall redis && \
    install-php-extensions igbinary redis
```

I verified that end to end — it gives you `Available serializers => php, json, igbinary` and `Available compression => lzf, zstd, lz4`.

> why is redis bundled with swoole?

It was requested in #33 and has been in the images since 4.8.12+/5.0.1+, to make it easy to start playing with Swoole without building extensions first. The README has a snippet for removing it if you don't want it.

## What changed as a result of this issue

Digging into this turned up a separate problem: the redis build options had quietly drifted. Our `--configureoptions` string was written for phpredis 5.3.7, and the three options phpredis added in 6.x were being answered by PECL's interactive prompt defaults rather than by our config. All six options are now listed explicitly, and the two that cost nothing to enable are on:

```
Available serializers => php, json
Available compression => lzf, zstd
```

That's in the 6.1.10 and 6.2.2 images and in the nightly images. To be clear, it does **not** fix what you reported — igbinary still isn't there.

## Plan for igbinary

Enabling the igbinary serializer means shipping the `igbinary` extension in the image: phpredis calls `igbinary_serialize()`/`igbinary_unserialize()` and registers a hard module dependency on it, so there's no way to have `Redis::SERIALIZER_IGBINARY` without `extension_loaded('igbinary')` also becoming true. Adding an extension has broken people's code here before (see #33, where the newly-present redis extension changed Doctrine's behavior in production), so this goes into a new minor series rather than a patch release: **Swoole 6.3.0**.

One blocker before that can happen — igbinary 3.2.16, the current stable release, doesn't compile on PHP 8.5:

```
src/php7/php_igbinary.h:35:10: fatal error: ext/standard/php_smart_string.h: No such file or directory
```

PHP 8.5 support is in 3.2.17RC1 only (igbinary PRs #403/#404). Our images build 8.5, so this waits for igbinary 3.2.17 stable.

Until then, the uninstall/reinstall snippet above is the answer. Keeping this open until igbinary ships in 6.3.0.

---

*Investigated and drafted with [Claude Code](https://claude.com/claude-code); the findings, builds and image tests referenced above were run and verified locally.*

**Comment by liulyn** [comment]
邮件已收到 谢谢！
